### ISSUE TITLE
No Tray icon in XFCE

### ISSUE THREAD

**Issue by Csokis** [dangeredwolf/ModernDeck#370]
Hi!

Unfortunately, the new version does not show the icon in the system tray! It was fine in the old version, but not in the new one :(

Arch Linux + XFCE

Please fix this before you stop developing! :)

Here is the error it shows in the terminal:
> Switching proxy to autodetect...
Switching proxy to autodetect...
Error: Failed to load image from path 'common/assets/img/app/Tray.png'
    at makeTray (/tmp/.mount_ModernZX9O2O/resources/app.asar/common/assets/js/moderndeck-electronhost.js:8:28806)
    at App.<anonymous> (/tmp/.mount_ModernZX9O2O/resources/app.asar/common/assets/js/moderndeck-electronhost.js:8:64025)
    at App.emit (node:events:526:28)
(node:14445) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at t.ipcRendererInternal.send (node:electron/js2c/renderer_init:85:328)
    at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:81:357)
(Use `moderndeck --trace-warnings ...` to show where the warning was created)
(node:14445) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Switching proxy to autodetect...
Switching proxy to autodetect...
Switching proxy to autodetect...
Client requested update check
Checking for update
Update for version 10.0.0 is not available (latest version: 10.0.0, downgrade is allowed).

**Comment by dangeredwolf** [comment]
Probably a regression in Electron. I think ModernDeck jumped from Electron
15 or 16 to 19 in version 10.0.0. I was originally going to ship it with Electron 20 but had severe issues with the renderer crashing and 21 had breaking API changes I hadn't worked out at that point. If I can upgrade to Electron 21 hopefully it'll resolve the issue.
